// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one

SELECT uid, name, email, created, updated FROM user WHERE uid = ?
`

// sqlc generate -f ./projects/closet/sqlc.yaml
func (q *Queries) GetUser(ctx context.Context, uid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, uid)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Name,
		&i.Email,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
