package views

import (
	"simple-server/pkg/util/gomutil"
	shared "simple-server/shared/views"

	x "github.com/glsubri/gomponents-alpine"
	h "maragu.dev/gomponents-htmx"

	. "maragu.dev/gomponents"
	. "maragu.dev/gomponents/components"
	. "maragu.dev/gomponents/html"
)

func Index(title string, groups map[string][]ClosetItem) Node {
	return HTML5(HTML5Props{
		Title:    title,
		Language: "ko",
		Head: gomutil.MergeHeads(
			shared.HeadsWithBeer(title),
			shared.HeadWithFirebaseAuth(),
			[]Node{
				Meta(Name("description"), Content("개인 옷장 관리 서비스")),
				Link(Rel("manifest"), Href("/manifest.json")),
				Script(Src("/static/closet.js"), Defer()),
			},
		),
		Body: []Node{
			shared.Snackbar(),

			Header(Class("primary"),
				Nav(
					A(Class("max"), Href("/"),
						H3(Text("Closet")),
					),
					A(ID("login"), Href("/login"), x.Data(""),
						x.Show("!$store.auth.isAuthed"),
						Text("로그인"),
					),
					A(ID("logout"), Href("#"), x.Data(""),
						x.Show("$store.auth.isAuthed"),
						Attr("onclick", "logoutUser()"),
						Text("로그아웃"),
					),
				),
			),

			Main(ID("closet-main"),
				Section(Class("stack gap-lg"),
					Div(Class("row gap-sm"),
						Button(Class("button"), Attr("onclick", "document.getElementById('upload-dialog').showModal()"), Text("내 옷장에 추가")),
						Button(Class("button outline"), Attr("onclick", "document.getElementById('search-dialog').showModal()"), Text("내 옷장에서 찾기")),
					),
					recommendCard(),
					ItemsSection(groups),
				),
			),

			uploadDialog(),
			searchDialog(),
		},
	})
}

func uploadDialog() Node {
	return Dialog(ID("upload-dialog"), x.Data(""),
		Div(Class("padding stack gap-sm"),
			H3(Class("title"), Text("내 옷장에 추가")),
			P(Class("caption"), Text("이미지와 태그를 입력하면 검색과 추천에 활용돼요.")),
			Div(x.Show("$store.auth.isAuthed"),
				Form(Class("stack gap-sm"), x.Data("{ mode: 'file', fileName: '' }"),
					h.Post("/items"),
					h.Target("#items-list"),
					h.Swap("outerHTML"),
					Attr("hx-encoding", "multipart/form-data"),
					EncType("multipart/form-data"),
					Attr("hx-on::after-request", "if (event.detail.successful) { this.reset(); if (this.__x) { this.__x.$data.fileName = ''; } document.getElementById('upload-dialog').close(); showInfo('새 옷을 추가했어요. 임베딩을 준비 중입니다.'); }"),
					h.On("htmx:response-error", "showError(event.detail.xhr.responseText || '업로드에 실패했어요. 다시 시도해주세요.');"),
					Div(Class("field label border"),
						Select(Name("kind"), Required(),
							Option(Value(""), Text("종류 선택"), Selected()),
							Option(Value("top"), Text("상의")),
							Option(Value("bottom"), Text("하의")),
							Option(Value("shoes"), Text("신발")),
							Option(Value("accessory"), Text("액세서리")),
						),
						Label(Text("종류")),
					),
					Div(Class("stack gap-xxs"),
						Div(Class("field label border"),
							Input(Type("text"), Name("tags")),
							Label(Text("태그")),
						),
						Small(Class("caption"), Text("콤마(,) 또는 줄바꿈으로 여러 태그를 입력해 주세요.")),
					),
					Div(Class("stack gap-xxs"),
						Span(Class("caption"), Text("이미지 입력 방식")),
						Div(Class("row gap-xs wrap"),
							Label(Class("chip"),
								Input(Type("radio"), Name("input_mode"), Value("file"), x.Model("mode"), Checked()),
								Span(Text("파일 업로드")),
							),
							Label(Class("chip"),
								Input(Type("radio"), Name("input_mode"), Value("url"), x.Model("mode"),
									x.On("change", "if ($event.target.checked && $refs.fileInput) { $refs.fileInput.value = ''; fileName = ''; }")),
								Span(Text("이미지 URL")),
							),
						),
					),
					Div(x.Show("mode === 'file'"), Class("stack gap-xxs"),
						Label(Style("display:inline-flex;align-items:center;gap:0.5rem;background:#ede7ff;color:#4d2fbf;border-radius:999px;padding:0.45rem 1rem;font-weight:600;cursor:pointer;"),
							I(Class("icon"), Text("attach_file")),
							Span(Text("이미지 선택")),
							Input(Type("file"), Name("image"), Accept("image/*"), x.Bind("required", "mode === 'file'"),
								x.Ref("fileInput"),
								x.On("change", "fileName = $event.target.files?.[0]?.name || ''"),
								Style("display:none;")),
						),
						Div(Class("caption"), x.Show("fileName"), x.Text("'선택한 파일: ' + fileName")),
					),
					Div(x.Show("mode === 'url'"), Class("stack gap-xxs"),
						Div(Class("field label"), Style("border:none;box-shadow:none;background:transparent;"),
							Input(Type("url"), Name("image_url"), x.Bind("required", "mode === 'url'"),
								Style("border:none;border-bottom:2px solid #6c5ce7;border-radius:0;background:transparent;padding-left:0;")),
							Label(Text("이미지 URL")),
						),
						Small(Class("caption"), Text("URL도 20MB 이하만 허용돼요.")),
					),
					Div(Class("row end gap-sm"),
						Button(Class("button"), Text("업로드")),
						Button(Class("button outline"), Type("button"), Attr("onclick", "document.getElementById('upload-dialog').close()"), Text("닫기")),
					),
				),
			),
			Div(x.Show("!$store.auth.isAuthed"), Class("stack gap-sm"),
				P(Class("caption"), Text("로그인해야 옷장을 만들 수 있어요.")),
				A(Class("button outline"), Href("/login"), Text("로그인하기")),
			),
		),
	)
}

func searchDialog() Node {
	return Dialog(ID("search-dialog"),
		Div(Class("padding stack gap-sm"),
			H3(Class("title"), Text("옷장 찾기")),
			P(Class("caption"), Text("원하는 태그와 종류로 빠르게 찾아보세요.")),
			Form(Class("stack gap-sm"),
				h.Get("/items"),
				h.Target("#items-list"),
				h.Swap("outerHTML"),
				h.Trigger("change delay:300ms, keyup changed delay:500ms, submit"),
				h.On("htmx:response-error", "showError(event.detail.xhr.responseText || '검색에 실패했어요.');"),
				Div(Class("field label border"),
					Select(Name("kind"),
						Option(Value(""), Text("전체"), Selected()),
						Option(Value("top"), Text("상의")),
						Option(Value("bottom"), Text("하의")),
						Option(Value("shoes"), Text("신발")),
						Option(Value("accessory"), Text("액세서리")),
					),
					Label(Text("종류")),
				),
				Div(Class("field label border"),
					Input(Type("text"), Name("tags")),
					Label(Text("태그")),
				),
				Div(Class("row gap-sm end"),
					Button(Class("button"), Type("submit"), Text("검색")),
					Button(Class("button outline"), Type("button"),
						Attr("onclick", "const form=this.form; form.reset(); document.getElementById('search-dialog').close();"),
						Text("닫기"),
					),
				),
				Img(Class("htmx-indicator"), Src("/shared/static/spinner.svg"), Alt("로딩 중")),
			),
		),
	)
}

func recommendCard() Node {
	return Article(Class("card"), x.Data(""),
		Div(Class("padding stack gap-sm"),
			H3(Class("title"), Text("AI 옷장 추천")),
			P(Class("caption"), Text("날씨와 스타일을 입력하면 가장 비슷한 조합을 추천해 드려요.")),
			Div(x.Show("$store.auth.isAuthed"),
				Form(Class("stack gap-sm"),
					h.Post("/recommend"),
					h.Target("#recommend-result"),
					h.Swap("innerHTML"),
					h.On("htmx:response-error", "showError(event.detail.xhr.responseText || '추천에 실패했어요.');"),
					Div(Class("field label border"),
						Input(Type("text"), Name("weather")),
						Label(Text("날씨")),
					),
					Div(Class("field label border"),
						Input(Type("text"), Name("style")),
						Label(Text("스타일")),
					),
					Div(Class("row end gap-sm"),
						Button(Class("button"), Type("submit"), Text("추천받기")),
					),
				),
				Div(ID("recommend-result")),
			),
			Div(x.Show("!$store.auth.isAuthed"), Class("stack gap-sm"),
				P(Class("caption"), Text("로그인하면 AI 추천을 받아볼 수 있어요.")),
				A(Class("button outline"), Href("/login"), Text("로그인하기")),
			),
		),
	)
}
