run:
  timeout: 5m

# https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    ## enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    ## disabled by default
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    # gomponents로 인해 함수가 길어지는 경향이 존재
    # - funlen
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - gosec
    - iface
    - makezero
    - mirror
    - musttag
    # Go 언어 특성상 명시적 IF가 많아짐
    # - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - protogetter
    - reassign
    - sloglint
    - sqlclosecheck
    - stylecheck
    - usetesting
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  stylecheck:
    dot-import-whitelist:
      - maragu.dev/gomponents
      - maragu.dev/gomponents/html
      - maragu.dev/gomponents/components
