version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    # gomponents로 인해 함수가 길어지는 경향이 존재
    # - funlen
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - gosec
    - govet
    - iface
    - ineffassign
    - makezero
    - mirror
    - musttag
    # Go 언어 특성상 명시적 IF가 많아짐
    # - nestif
    - nilerr
    - nilnesserr
    - nilnil
    # - noctx
    - nonamedreturns
    - nosprintfhostport
    - protogetter
    - reassign
    - sloglint
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    staticcheck:
      dot-import-whitelist:
        - maragu.dev/gomponents
        - maragu.dev/gomponents/html
        - maragu.dev/gomponents/components
  exclusions:
    presets:
      - legacy
      - std-error-handling
