-- +goose Up
CREATE TABLE IF NOT EXISTS user (
    uid TEXT PRIMARY KEY,
    name TEXT DEFAULT '' NOT NULL,
    email TEXT UNIQUE DEFAULT '' NOT NULL,
    created TEXT DEFAULT CURRENT_TIMESTAMP,
    updated TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS push_key (
    id TEXT DEFAULT (
        'r' || LOWER(HEX(RANDOMBLOB(7)))
    ) NOT NULL PRIMARY KEY,
    uid TEXT DEFAULT '' NOT NULL,
    token TEXT DEFAULT '' NOT NULL,
    created TEXT DEFAULT CURRENT_TIMESTAMP,
    updated TEXT DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE user;

DROP TABLE push_key;