// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Diary struct {
	ID         string
	Uid        string
	Date       string
	Content    string
	AiFeedback string
	AiImage    string
	Created    sql.NullString
	Updated    sql.NullString
	Mood       string
}

type User struct {
	Uid     string
	Name    string
	Email   string
	Created sql.NullString
	Updated sql.NullString
}

type UserSetting struct {
	Uid         string
	IsPush      int64
	PushToken   string
	PushTime    string
	RandomRange int64
	Created     sql.NullString
	Updated     sql.NullString
}
