// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
)

const createDiary = `-- name: CreateDiary :one
INSERT INTO diarys (uid, content, date, created, updated)
VALUES (?,
        ?,
        ?,
        datetime('now', 'localtime'),
        datetime('now', 'localtime'))
RETURNING content, created, date, id, uid, updated
`

type CreateDiaryParams struct {
	Uid     string
	Content string
	Date    string
}

// strftime('%Y%m%d', 'now', 'localtime'),
func (q *Queries) CreateDiary(ctx context.Context, arg CreateDiaryParams) (Diary, error) {
	row := q.db.QueryRowContext(ctx, createDiary, arg.Uid, arg.Content, arg.Date)
	var i Diary
	err := row.Scan(
		&i.Content,
		&i.Created,
		&i.Date,
		&i.ID,
		&i.Uid,
		&i.Updated,
	)
	return i, err
}

const getDiary = `-- name: GetDiary :one

SELECT content, created, date, id, uid, updated
FROM diarys
WHERE date = ?
  AND uid = ?
LIMIT 1
`

type GetDiaryParams struct {
	Date string
	Uid  string
}

// sqlc generate -f ./projects/deario/sqlc.yaml
func (q *Queries) GetDiary(ctx context.Context, arg GetDiaryParams) (Diary, error) {
	row := q.db.QueryRowContext(ctx, getDiary, arg.Date, arg.Uid)
	var i Diary
	err := row.Scan(
		&i.Content,
		&i.Created,
		&i.Date,
		&i.ID,
		&i.Uid,
		&i.Updated,
	)
	return i, err
}

const getDiaryRandom = `-- name: GetDiaryRandom :one
SELECT content, created, date, id, uid, updated
FROM diarys
WHERE date IS NOT NULL
  AND uid = ?
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetDiaryRandom(ctx context.Context, uid string) (Diary, error) {
	row := q.db.QueryRowContext(ctx, getDiaryRandom, uid)
	var i Diary
	err := row.Scan(
		&i.Content,
		&i.Created,
		&i.Date,
		&i.ID,
		&i.Uid,
		&i.Updated,
	)
	return i, err
}

const listDiarys = `-- name: ListDiarys :many
SELECT content, created, date, id, uid, updated
FROM diarys
WHERE uid = ?
ORDER BY created desc
LIMIT 10 OFFSET ((? - 1) * 10)
`

type ListDiarysParams struct {
	Uid     string
	Column2 interface{}
}

func (q *Queries) ListDiarys(ctx context.Context, arg ListDiarysParams) ([]Diary, error) {
	rows, err := q.db.QueryContext(ctx, listDiarys, arg.Uid, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Diary
	for rows.Next() {
		var i Diary
		if err := rows.Scan(
			&i.Content,
			&i.Created,
			&i.Date,
			&i.ID,
			&i.Uid,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiary = `-- name: UpdateDiary :one
UPDATE diarys
set content = ?,
    updated = datetime('now')
WHERE id = ?
RETURNING content, created, date, id, uid, updated
`

type UpdateDiaryParams struct {
	Content string
	ID      string
}

func (q *Queries) UpdateDiary(ctx context.Context, arg UpdateDiaryParams) (Diary, error) {
	row := q.db.QueryRowContext(ctx, updateDiary, arg.Content, arg.ID)
	var i Diary
	err := row.Scan(
		&i.Content,
		&i.Created,
		&i.Date,
		&i.ID,
		&i.Uid,
		&i.Updated,
	)
	return i, err
}
