// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Category struct {
	ID           string
	Uid          string
	Name         string
	Role         string
	ParentID     sql.NullString
	DisplayOrder int64
}

type PushKey struct {
	ID      string
	Uid     string
	Token   string
	Created sql.NullString
	Updated sql.NullString
}

type User struct {
	Uid     string
	Name    string
	Email   string
	Created sql.NullString
	Updated sql.NullString
}
