// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type PushKey struct {
	ID      string
	Uid     string
	Token   string
	Created sql.NullString
	Updated sql.NullString
}

type User struct {
	Uid     string
	Name    string
	Email   string
	Created sql.NullString
	Updated sql.NullString
}
