name: golangci-lint

on:
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Generate .env File
        run: |
          cat <<EOF > .env
            ENV=prod
          EOF

      - name: Install Templ Dependencies
        run: |
          export PATH=$PATH:$HOME/go/bin
          go install github.com/a-h/templ/cmd/templ@latest

      - name: Templ Generate
        run: |
          templ generate

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
